name: coffee_shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.4.10
  flutter_stripe: ^10.0.0
  stripe_android: ^10.0.0
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  http: ^1.2.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/.env

