// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWt7vY0Y_YHA8aset5ujUWdN8iR_3tgQA',
    appId: '1:130988029550:web:e2da5ac977f86f0f8a587f',
    messagingSenderId: '130988029550',
    projectId: 'coffee-shop-a4548',
    authDomain: 'coffee-shop-a4548.firebaseapp.com',
    storageBucket: 'coffee-shop-a4548.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRc5Pkzw4RuAdL3sMRrZpw65HZTc6SYz4',
    appId: '1:130988029550:android:4da947fafdf0f09e8a587f',
    messagingSenderId: '130988029550',
    projectId: 'coffee-shop-a4548',
    storageBucket: 'coffee-shop-a4548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNL7r-g8jTvC5BtuyKctQj8-2sVUUFoy8',
    appId: '1:130988029550:ios:bda89d7034ed40528a587f',
    messagingSenderId: '130988029550',
    projectId: 'coffee-shop-a4548',
    storageBucket: 'coffee-shop-a4548.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNL7r-g8jTvC5BtuyKctQj8-2sVUUFoy8',
    appId: '1:130988029550:ios:5669cbf7942ad9088a587f',
    messagingSenderId: '130988029550',
    projectId: 'coffee-shop-a4548',
    storageBucket: 'coffee-shop-a4548.appspot.com',
    iosBundleId: 'com.example.coffeeShop.RunnerTests',
  );
}
